import Head from "next/head";
import styles from "../styles/Home.module.css";
import config from "../config";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.title}>
        Welcome, Please choose one application from the list.
      </div>
      <div className={styles.cardsWrapper}>
        {config.map((item) => (
          <div className={styles.card} key={item.route}>
            <Link href={item.route}>{item.name}</Link>
          </div>
        ))}
      </div>
    </div>
  );
}
